### ISSUE TITLE
Option to make validation errors fatal

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#100]
Proceeding after getting validation errors can freeze the system. One really should fix those before running code on GPU.

**Comment by dpwiz** [comment]
Hm.. I copied the cbits for `debugCallbackPtr` and made them fatal. But then I found it wasn't actually used at all and it is something else that puts[1] those nicely formatted validation errors:

```
UNASSIGNED-CoreValidation-DrawState-DescriptorSetNotUpdated(ERROR / SPEC): msgNum: 0 - Descriptor set 0x2d bound as set #0 encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding #1 at global descriptor index 1 is being used in draw but has not been updated.
    Objects: 1
        [0] 0x2d, type: 23, name: NULL
UNASSIGNED-CoreValidation-DrawState-InvalidVtxAttributeAlignment(ERROR / SPEC): msgNum: 0 - Invalid attribAddress alignment for vertex attribute 1 from pipeline (0x2c) and vertex buffer (0x9).
    Objects: 1
        [0] 0x9, type: 9, name: NULL
UNASSIGNED-CoreValidation-DrawState-InvalidVtxAttributeAlignment(ERROR / SPEC): msgNum: 0 - Invalid attribAddress alignment for vertex attribute 2 from pipeline (0x2c) and vertex buffer (0x9).
    Objects: 1
        [0] 0x9, type: 9, name: NULL
```

I'd prefer more color in there, but, anyway, this hints that this mighty someone may stop the program if asked nicely.

[1]: even if I remove my debugCallbackInfo entirely, huh 🤔

**Comment by expipiplus1** [comment]
Ah, you might not be creating a debug utils messenger object. You need to create one in (the one created with the instance is just for catching instance creation/destruction errors I believe). I should add this to the examples

**Comment by dpwiz** [comment]
Ha. That helped and I can see my VMA spam again (=

> The one created with the instance is just for catching instance creation/destruction errors I believe.

The error messages from before were thrown at me during commandBuffer creation.

**Comment by dpwiz** [comment]
I tested my deadly callback and it did promptly shot the program before it could shot my PC.
