### ISSUE TITLE
Question: `withAsyncBound` and SDL

### ISSUE THREAD

**Issue by lancelet** [expipiplus1/vulkan#118]
I've been working on getting the examples to run on macOS under MoltenVK (using the standard macOS Vulkan SDK). I have a question about `withAsyncBound`.

Before I started tinkering, the status of the examples (checked means working) on macOS is:
- [x] compute
- [x] info
- [x] offscreen
- [ ] resize
- [ ] sdl-triangle

I've made some changes necessary to get the `sdl-triangle` example working in this commit: https://github.com/lancelet/vulkan/commit/255baa7dcc11f040ee5d41586c1765190a7decc4
A couple of the changes just involve using Vulkan 1.0 API calls (since that seems to be all that MoltenVK supports; anything else causes a segfault).

However, I can't get the example to work using `withAsyncBound`. If I leave that in, then during the initial creation of the window, I see this from SDL:
```
Assertion failed: (NSViewIsCurrentlyBuildingLayerTreeForDisplay() != currentlyBuildingLayerTree), function NSViewSetCurrentlyBuildingLayerTreeForDisplay, file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1894.40.150/AppKit.subproj/NSView.m, line 13568.
```
If I push `withAsyncBound` down so that it only includes the main application loop then the window is initialized correctly but the main loop produces:
```
2020-05-24 20:07:11.771 sdl-triangle[57651:897931] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff31d34d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6a8bf5bf objc_exception_throw + 48
	2   AppKit                              0x00007fff2ef34fd5 +[NSEvent _discardTrackingAndCursorEventsIfNeeded] + 0
	3   libSDL2-2.0.0.dylib                 0x0000000101e054ca Cocoa_PumpEvents + 138
	4   libSDL2-2.0.0.dylib                 0x0000000101d5271b SDL_WaitEventTimeout_REAL + 203
	5   sdl-triangle                        0x0000000101ad2062 sdl2zm2zi5zi2zi0zmB5N2QlaVtRD8YE5cKxrWAf_SDLziEvent_pollEvent1_info + 114
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Is there a reason to require `withAsyncBound`? I couldn't see an example in the [Haskell SDL2 repository](https://github.com/haskell-game/sdl2) that uses this function, although there are numerous examples (see [here](https://github.com/haskell-game/sdl2/blob/715eef81b0193d2aae0d8f563cca889f54ee6955/examples/lazyfoo/Lesson03.hs#L27) for one) that call `pollEvents` without using it. If it is necessary, is there any special magic to get it to work on macOS?

**Comment by expipiplus1** [comment]
I was just going by the comment here https://hackage.haskell.org/package/sdl2-2.5.0.0/docs/SDL-Event.html#v:pollEvent (and here https://wiki.libsdl.org/SDL_PollEvent) which specify that `pollEvents` should always be called from the thread which sets up the window. I think without this I was getting no results from `pollEvents` half the time.

For the second error: I guess the new bound thread is not "main" enough for OS X.

**Comment by expipiplus1** [comment]
Ah, seems as though the main thread is bound by default (according to #haskell). So the withAsyncBound can probably go

**Comment by lancelet** [comment]
Thanks for looking into it. I'll prepare PRs to get the examples running on macOS.
