### ISSUE TITLE
Missing vulkan-headers when building VulkanMemoryAllocator

### ISSUE THREAD

**Issue by vyorkin** [expipiplus1/vulkan#119]
Not sure how/why exactly that happens, because I can see that `vulkan-headers` library should be there: https://github.com/expipiplus1/vulkan/blob/master/default.nix#L134

But for some reason, it can't find the required headers:
```sh
builder for '/nix/store/g0b479rkx7i8hwa6bjrh9gzcin7jxdlw-VulkanMemoryAllocator-0.3.drv' failed with exit code 1; last 10 log lines:
  
  VulkanMemoryAllocator/src/vk_mem_alloc.h:1942:14: error:
       fatal error: vulkan/vulkan.h: No such file or directory
       1942 |     #include <vulkan/vulkan.h>
            |              ^~~~~~~~~~~~~~~~~
       |
  1942 |     #include <vulkan/vulkan.h>
       |              ^
  compilation terminated.
  `cc' failed in phase `C Compiler'. (Exit code: 1)
```

In my case, the fix was to add `vulkan-headers` to the `extraLibraries` by:

```nix
(pkgs.haskell.lib.addExtraLibrary VulkanMemoryAllocator pkgs.vulkan-headers)
```

**Comment by TristanCacqueray** [comment]
When building using `stack build` directly, it fails with:
```
$ stack build
Specified file "VulkanMemoryAllocator/src/vk_mem_alloc.h" for extra-source-files does not exist
VulkanMemoryAllocator> configure (lib)
VulkanMemoryAllocator> Configuring VulkanMemoryAllocator-0.3.1...
VulkanMemoryAllocator> Warning: 'include-dirs: VulkanMemoryAllocator/src' directory does not exist.
            
Warning: File listed in VulkanMemoryAllocator/VulkanMemoryAllocator.cabal file does not exist: VulkanMemoryAllocator/src/vk_mem_alloc.h
VulkanMemoryAllocator> build (lib)
VulkanMemoryAllocator> Preprocessing library for VulkanMemoryAllocator-0.3.1..
VulkanMemoryAllocator> Building library for VulkanMemoryAllocator-0.3.1..
VulkanMemoryAllocator> 
VulkanMemoryAllocator> /solid/data/git/github.com/expipiplus1/vulkan/VulkanMemoryAllocator/src/lib.cpp:9:10: error:
VulkanMemoryAllocator>      fatal error: vk_mem_alloc.h: No such file or directory
VulkanMemoryAllocator>         9 | #include <vk_mem_alloc.h>
VulkanMemoryAllocator>           |          ^~~~~~~~~~~~~~~~
VulkanMemoryAllocator>   |
VulkanMemoryAllocator> 9 | #include <vk_mem_alloc.h>
VulkanMemoryAllocator>   |          ^
VulkanMemoryAllocator> compilation terminated.
VulkanMemoryAllocator> `gcc' failed in phase `C Compiler'. (Exit code: 1)
```

Downloading https://raw.githubusercontent.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/master/src/vk_mem_alloc.h to `VulkanMemoryAllocator/src/vk_mem_alloc.h` fixed the issue.

**Comment by expipiplus1** [comment]
@TristanCacqueray you can do that by initializing git submodules. I wish git was more vocal when they are missing...

**Comment by expipiplus1** [comment]
@vyorkin very strange, could you provide some commands to reproduce please?

Building VulkanMemoryAllocator with nix is done as part of the CI, https://github.com/expipiplus1/vulkan/runs/703824872?check_suite_focus=true for example. I also use nix for day to day development and its always worked for me

**Comment by TristanCacqueray** [comment]
@expipiplus1 oh right, i didn't fully read the readme, running `git submodule update --init VulkanMemoryAllocator/VulkanMemoryAllocator` fixed that. Thanks, the example are working great!

**Comment by expipiplus1** [comment]
@vyorkin 
 
> In my case, the fix was to add `vulkan-headers` to the `extraLibraries` by:
> 
> ```nix
> (pkgs.haskell.lib.addExtraLibrary VulkanMemoryAllocator pkgs.vulkan-headers)
> ```

Where exactly are you adding this line? `VulkanMemoryAllocator` doesn't appear on the RHS of any bindings in any of the nix expressions.

**Comment by vyorkin** [comment]
Here is the example repo to reproduce: https://github.com/vyorkin/hiss

**Comment by expipiplus1** [comment]
Ah I see, this is for another project. The correct fix would be to put this extra dependency in the nixpkgs repo. I've opened a PR here: https://github.com/NixOS/nixpkgs/pull/89160

This is indeed the same thing I do for the `examples` `default.nix` https://github.com/expipiplus1/vulkan/blob/a939a13cc262eb441c09c661cafd40010c1eddcd/examples/default.nix#L42-L45

**Comment by expipiplus1** [comment]
Closed by https://github.com/NixOS/nixpkgs/pull/89160

**Comment by vyorkin** [comment]
Awesome! Thank you
