### ISSUE TITLE
Building with haskell.nix

### ISSUE THREAD

**Issue by locallycompact** [expipiplus1/vulkan#130]
Hi, I've been trying to build this with stack-to-nix and I raised an issue there, and they say the issue may be that the VulkanMemoryAllocator does not declare a dependency on vulkan-headers.

https://github.com/input-output-hk/haskell.nix/issues/674

**Comment by expipiplus1** [comment]
I think this is an issue with haskell.nix and not this package as I don't think cabal specifies any way to specify a dependency such as the vulkan-header one which isn't a library and doesn't necessarily have a pkg-config description.

I'm happy to make any changes to VMA here though if it would help.

For anyone else reading, the discussion has been taking place here: input-output-hk/haskell.nix#674
