### ISSUE TITLE
Remove vectors and OverloadedLists

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#145]
I remember you said there is no special reason to stick with the Vector in structures.

I haven't met any places so far where I did anything more vector-y than `Vector.singleton` and `Vector.fromList`. I have some places for indexed access, but that is outside the API.

So, what's the status on this?

**Comment by expipiplus1** [comment]
Just need to decide if the breaking change and performance implications (could be good or bad) are worth it. The implementation would probably be fairly simple, just go through `generate-new` and think about every use of this constructor: https://github.com/expipiplus1/vulkan/blob/v3.6.2/generate-new/src/Marshal/Scheme.hs#L62, specifically changing vector functions to list functions (`generateM`, `Data.Vector.length`).

Other points in the design space would be to use storable or unboxed vectors where possible (probably not worth the hassle though).

**Comment by dpwiz** [comment]
I see that code does some length-tracking. Keeping Vectors would be beneficial indeed. Deferring counting items until actual allocation will be quite brittle if possible.

**Comment by expipiplus1** [comment]
well, every use of vectors is O(n) anyway (all the elements are poked), so in terms of complexity it doesn't make any difference.

This would be best revisited once there is some good benchmark which spends significant time in `vulkan`

**Comment by dpwiz** [comment]
I had performance issues around constructing and poking Vector.Storable (in my OpenGL app) but that usually means I should construct and poke less, not more efficiently.

**Comment by dpwiz** [comment]
`ByteArray#` of course is a game-changer (☺️) and allows to pack much more stuff... until it doesn't and you have to reconsider your code anyway.
