### ISSUE TITLE
Shader quasiquoters could use some basic interpolation

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#148]
I've found one package without haskell-src-foo dependencies: https://hackage.haskell.org/package/neat-interpolation

While unstructured code generation is a thing to be avoided, at least some basic constant injection could be a force for good where specialization constants are too awkward.

Further improvements will be possible with `language-c-quote` piled upon simple text injection.

**Comment by expipiplus1** [comment]
Great idea!

**Comment by dpwiz** [comment]
Aw, shucks! It only exposes `Q Exp` bundle.  I'll go ask to open it up.

**Comment by expipiplus1** [comment]
FWIW I've enjoyed using http://hackage.haskell.org/package/interpolatedstring-perl6-1.0.2 in the past.

**Comment by dpwiz** [comment]
For the record: by splicing `$(compileShaderQ "frag" code)` it is possible to use pretty much any template system (e.g. mustache) to generate shader code. You'll lose the shader line errors though. But those can be recovered with CPP and `__LINE__` pragmas inside the template. Another trade-off is that the `code` should be located elsewhere to be used inside splices.

**Comment by expipiplus1** [comment]
You could do `$(compileShaderQ "frag" [q|main{...}|])` then the code could be right there. There's no `SpliceE` in template-haskell's `Exp` type, so it can't just be `[frag|code with interpolated variables|]`
