### ISSUE TITLE
Publish vulkan-utils

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#169]
It's quite stable, from what I've seen. And useful. And cloning the whole vulkan repo just for one subdir seems wasteful... Time for a Hackage upload?

**Comment by expipiplus1** [comment]
Good idea. I think I'll try and factor out some of the really common code in the examples.

If I don't get round to that this weekend I'll probably upload an initial early version anyway

**Comment by expipiplus1** [comment]
candidate up at https://hackage.haskell.org/package/vulkan-utils-0.1.2/candidate

Will release once https://github.com/expipiplus1/vulkan/pull/174 merges

**Comment by expipiplus1** [comment]
Released!
