### ISSUE TITLE
Enabling split-sections breaks linker on Windows

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#183]
Add `-split-sections` to `ghc-options` and the final step of building the `vulkan` package crashes with "too many sections" error.

**Comment by expipiplus1** [comment]
Hmm, that's probably quite an important option! Maybe it would be worth
looking into generating this package with fewer extensions?

Would the linker issue tracker be a better place? Or GHC?

Does this happen on Linux?

**Comment by dpwiz** [comment]
I think it's a GHC issue really. But maybe there is something that can be done about it on the package side.

Is it possible to extract API version layers into their own packages?
Like `vulkan-base` -> `vulkan-core10` -> `vulkan-core11`, etc.

This may help with haddock symbol search too.

**Comment by dpwiz** [comment]
Linux builds just fine and the size reduction is impressive.

**Comment by dpwiz** [comment]
Ha, there's a [SO question](https://stackoverflow.com/questions/64287505/ld-too-many-sections-90295) popped up almost at the same time.

**Comment by expipiplus1** [comment]
But maybe there is something that can be done about it on the package side.
> 
> Is it possible to extract API version layers into their own packages?
> Like `vulkan-base` -> `vulkan-core10` -> `vulkan-core11`, etc.

Perhaps some of the more interesting cabal features could help, like sub packages? 

Just cutting out extension modules probably won't work, as they're all tied together a little bit (with the struct extending machinery). I suspect that removing them from the spec xml file will cause the source generation to break (some names in extensions are referred to explicitly).

> This may help with haddock symbol search too.

How so, I've not had any issues with this so far.

**Comment by expipiplus1** [comment]
Certainly shouldn't be impossible to generate the package with fewer extensions however

**Comment by expipiplus1** [comment]
> Linux builds just fine and the size reduction is impressive.

Feel free to make a PR for the readme mentioning this!

**Comment by expipiplus1** [comment]
Can reproduce, in fact I'm not able to compile sdl2 with split sections either.

**Comment by expipiplus1** [comment]
Compiling the examples with cabal and `--enable-split-sections` works, and the size reduction is indeed considerable after stripping (29MB to 5MB for the `info` example).

This looks to be a bug in stack. 

Thanks to AndreasK!
