### ISSUE TITLE
AccelerationStructureInstanceKHR has no Storable instance

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#209]
It's not created because of the transformation matrix...

**Comment by sheaf** [comment]
Isn't it because of the bit fields? The transformation matrix has its own Storable instance, so why would that be an issue?
The bit field issue is one I've been running into, trying to update the bindings for the `vulkan-api` package, but it is becoming a bit tiresome so I'm thinking of switching to using this library which looks much improved since I last looked at it over a year ago.

**Comment by expipiplus1** [comment]
A storable instance is only created if all of the [members are "poked" simply (i.e. they are poked in IO)](https://github.com/expipiplus1/vulkan/blob/4af025f7bddda19a5ca30c35ca87244b6d477c0b/generate-new/src/Render/Struct.hs#L208). The transformation matrix is a struct, and at the moment is treated conservatively. 

Basically this line needs to be: Is this a structOrUnion and doesn't have a storable instance
https://github.com/expipiplus1/vulkan/blob/4af025f7bddda19a5ca30c35ca87244b6d477c0b/generate-new/src/Render/Stmts/Utils.hs#

**Comment by expipiplus1** [comment]
"treated conservatively" because it could need to `alloca` or something in it's poke routine.

It happens that TransformationMatrix doesn't do this. The solution is to make the generator aware of this at the time that the poker for `AccelerationStructureInstanceKHR` is generated. Probably the easiest way to do this is to render the structs in dependency order and keep track of which ones have storable instances.

Yeah, the bitfields didn't fall out naturally, in the end I just wrote a bespoke renderer for them and that works fine: https://github.com/expipiplus1/vulkan/blob/4af025f7bddda19a5ca30c35ca87244b6d477c0b/generate-new/src/Bespoke.hs#L490-L575 (It's not the tidest bit of the generator sadly)

**Comment by expipiplus1** [comment]
The storable instance is easy to write by hand though:

```
    instance Storable AccelerationStructureInstanceKHR where
      sizeOf ~_ = 64
      alignment ~_ = 8
      peek = peekCStruct
      poke ptr poked = pokeCStruct ptr poked (pure ())
```

**Comment by expipiplus1** [comment]
> issue is one I've been running into, trying to update the bindings

The ray tracing extension was definitely the one with the most work involved, so many complexities, like the `ppGeometries` stuff and `ppOffsetInfos`, although I think most of that was because of their specific requirements regarding the smart marshaling this package does.

**Comment by expipiplus1** [comment]
@sheaf, are you on IRC? would be great to chat about the interesting work on your spir-v compiler.

**Comment by sheaf** [comment]
@expipiplus1 Happy to chat, let me know where to find you!

**Comment by expipiplus1** [comment]
I'm on #haskell at the moment, nick is `jophish`
