### ISSUE TITLE
Zero instance for TransformMatrixKHR

### ISSUE THREAD

**Issue by sheaf** [expipiplus1/vulkan#240]
The current `Zero` instance for `TransformMatrixKHR` doesn't abide by the specification:

```haskell
instance Zero TransformMatrixKHR where
  zero = TransformMatrixKHR
           (zero, zero, zero, zero)
           (zero, zero, zero, zero)
           (zero, zero, zero, zero)
```

> - The first three columns of matrix must define an invertible 3x3 matrix

If possible, the instance should be changed to

 ```haskell
instance Zero TransformMatrixKHR where
  zero = TransformMatrixKHR
           (1,0,0,0)
           (0,1,0,0)
           (0,0,1,0)
```

However, if for any reason that's annoying, I think it would be better to remove the instance entirely.

**Comment by expipiplus1** [comment]
Removing it would cause VkAccelerationStructureInstanceKHR to lose its zero
instance too which is sad.

It's not too annoying to implement like that but I think it's a bit weird!

There are probably other zero instances with the same problem, like struts
with non optional arrays (which are currently empty)

**Comment by expipiplus1** [comment]
I think the zero instance should be left as it is. But we could consider adding an 'Identity'/'One' class for this and some other things (such as `Quaternionf` http://expipiplus1.github.io/vulkan/openxr-0.1-docs/OpenXR-Core10-Space.html#v:Quaternionf)

**Comment by sheaf** [comment]
Well I don't really see the point of the `Zero` instance as it is, as one would never want to use it. I suppose the perspective of `zero should mean all the bits are 0` justifies it, but I don't find it very convincing. I think `zero` should provide a default value whenever there exists a unique possible default value; in this case we want a multiplicative identity as opposed to an additive identity.

**Comment by expipiplus1** [comment]
Yeah, you're right, it's actually only useful for satisfying that law which is pretty flimsy anyway, shouldn't be too hard to make the change.
