### ISSUE TITLE
Computation of requirements: min version numbers too high

### ISSUE THREAD

**Issue by sheaf** [expipiplus1/vulkan#249]
I've just run into the issue that updating the `vulkan` package has caused my programs to stop working because the min version requirements were increased. It also took me ages to debug because the error message was

```
Required requirements not met:
  Couldn't find device extension: "VK_KHR_deferred_host_operations"
```

which doesn't indicate that the issue was with a minimum version number.    

I don't think the min version should be `SPEC_VERSION`; maybe it's just better to set it to 0?

**Comment by expipiplus1** [comment]
At the very least that error message should be improved!
