### ISSUE TITLE
createInstanceFromRequirements throws an error on unsatisfied optional constraints

### ISSUE THREAD

**Issue by sheaf** [expipiplus1/vulkan#254]
`createInstanceFromRequirements` [contains the following line](https://github.com/expipiplus1/vulkan/blob/9093e150c24c01ad5c8c76c63af90fdc84720e4d/utils/src/Vulkan/Utils/Initialization.hs#L110
):

```haskell
traverse_ sayErr (requirementReport rrs ors)
```

Unless I'm missing something, this means that an error is thrown whenever there is anything at all to report, including only missing optional requirements.    

I noticed this as `createDebugInstanceFromRequirements` threw an error with a device on which `VK_LAYER_KHRONOS_validation` is not present, but the older `VK_LAYER_LUNARG_standard_validation` is.

**Comment by expipiplus1** [comment]
`sayErr` just prints to stderr: https://github.com/expipiplus1/vulkan/blob/d27a6627e6a16d8afddf6e5fcd90c582fa98980a/utils/src/Vulkan/Utils/Internal.hs#L25-L26

Looks similar to https://github.com/expipiplus1/vulkan/issues/229 I guess just some small logic error
