### ISSUE TITLE
Current roadmap?

### ISSUE THREAD

**Issue by o1lo01ol1o** [expipiplus1/vulkan#26]
Hi, 
  What's the current roadmap for this library?  I've seen some mention of higher-level abstractions, do those exist anywhere?  (Or is there at least some documentation on how those might exist somewhere?) . 

Sweet, thanks

**Comment by expipiplus1** [comment]
Sadly I don't have to time to maintain this at the moment. Hopefully this
will be changing in a month or so. Sorry :-(

**Comment by o1lo01ol1o** [comment]
No worries, ping back when you have an update? 

thx

**Comment by expipiplus1** [comment]
I've set a reminder. Thanks for the interest!
