### ISSUE TITLE
Is this overflowed-literals warning in `vulkan` needs to be fixed?

### ISSUE THREAD

**Issue by ukari** [expipiplus1/vulkan#266]
### problem
I noticed a [warning](https://github.com/expipiplus1/vulkan/pull/263/checks?check_run_id=1992881307#step:15:669) in github ci log
```
src/Vulkan/Extensions/VK_KHR_synchronization2.hs:5294:78: warning: [-Woverflowed-literals]
    Literal 4294967296 is out of the Word32 range 0..4294967295
     |
5294 | pattern ACCESS_2_SHADER_SAMPLED_READ_BIT_KHR            = AccessFlagBits2KHR 0x100000000
     |                                                                              ^^^^^^^^^^^

src/Vulkan/Extensions/VK_KHR_synchronization2.hs:5302:78: warning: [-Woverflowed-literals]
    Literal 8589934592 is out of the Word32 range 0..4294967295
     |
5302 | pattern ACCESS_2_SHADER_STORAGE_READ_BIT_KHR            = AccessFlagBits2KHR 0x200000000
     |                                                                              ^^^^^^^^^^^
```

I check [vulkan doc](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPipelineStageFlagBits2KHR.html), and found that `VkPipelineStageFlagBits2KHR` has a ULL(unsigned long long) type which means `Word64` instead of `Word32` in haskell.
``` c
static const VkPipelineStageFlags2KHR VK_PIPELINE_STAGE_2_CLEAR_BIT_KHR = 0x800000000ULL;
```

### related code

[`PipelineStageFlagBits2KHR`](https://github.com/expipiplus1/vulkan/blob/4f163a3cc35d4fc5156e8bc6c33ab75ba7368c0d/src/Vulkan/Extensions/VK_KHR_synchronization2.hs#L5437)
``` haskell
newtype PipelineStageFlagBits2KHR = PipelineStageFlagBits2KHR Flags
  deriving newtype (Eq, Ord, Storable, Zero, Bits, FiniteBits)
```
[`PIPELINE_STAGE_2_CLEAR_BIT_KHR`](https://github.com/expipiplus1/vulkan/blob/4f163a3cc35d4fc5156e8bc6c33ab75ba7368c0d/src/Vulkan/Extensions/VK_KHR_synchronization2.hs#L5568)
``` haskell
pattern PIPELINE_STAGE_2_CLEAR_BIT_KHR                          = PipelineStageFlagBits2KHR 0x800000000
```

[`Flags`](https://github.com/expipiplus1/vulkan/blob/4f163a3cc35d4fc5156e8bc6c33ab75ba7368c0d/src/Vulkan/Core10/FundamentalTypes.hs#L608)
``` haskell
type Flags = Word32
```

**Comment by expipiplus1** [comment]
Yeah, this certainly should be fixed! I'll get to it asap I hope.

Basically these should use Flags64 instead.

**Comment by expipiplus1** [comment]
This is fixed and released on Hackage
