### ISSUE TITLE
High level bindings ideas

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#28]
A dump of ideas for higher level bindings:

- [x] In the spec parameters are marked as optional or not, it would be nicer to use `Maybe` for these rather than null pointer/zero values.
- [x] Passing values in via const pointers is a pain, it shouldn't be that hard at all to write wrappers for all the commands. The wrapper would take a Haskell struct and do the `alloca` dance for the user. The spec suggests that this is a safe thing to do for all the const pointers used in the spec.
- [x] In correspondence with the above idea, getting values out my passing non-const pointers to parameters is a pain too, the wrappers could perform the allocation and `peek` and return all the outputs in a tuple.
- [x] Storing `sType` in all the records is a bit silly as they can only have one possible value. Should this even be removed from the low level bindings?
- [x] Struct chains shouldn't be that hard to implement in Haskell as some kind of `vinyl` like heterogeneous list.
- [x] Pairs of functions (`vkCreateXXX`/`vkDestroyXXX`, `vkAllocateXXX`/`vkFreeXXX`) could be made into a `withXXX` function which makes sure that destruction takes place with `bracket`.

Bikeshedding:

- Should this be in a new library (`vulkan-easy`/`vulkan-wrappers` or something) or in this library `Graphics.Vulkan.Easy....`

**Comment by expipiplus1** [comment]
Wrappers should also take care of passing in size/pointer pairs or null terminated lists.

**Comment by achirkin** [comment]
A few findings from my attempts to make bindings:

 * `sType` could work as an RTTI singleton. Although it is hard to imagine a use case in vulkan for that :)
 * One option to handle the most annoying `CString` pointers is to allocate them statically and make [explicitly bidirectional pattern synonyms with view patterns](https://github.com/achirkin/vulkan/blob/master/vulkan-api/src-gen/Graphics/Vulkan/Ext/VK_KHR_swapchain.hs#L1048). This way you can compare them, pattern-match, and put into vulkan structures safely.
 * Nesting too many `withXXX` functions and some point become [really awkward](https://github.com/achirkin/vulkan/blob/master/vulkan-examples/06-Drawing.hs#L38) :) I tried an [alternative approach](https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib.hs#L24) based on a [continuation monad](https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib/Program.hs) giving a very convenient way to control the scope of resource allocation, but this is hard to combine with vanilla exceptions.

**Comment by expipiplus1** [comment]
Thanks!

I suppose sType could be used to recover structs from struct-chains, perhaps.

That CString pattern is nice!

What's the difference between your `Program` monad and `ResourceT` (+ some state)? 
https://hackage.haskell.org/package/resourcet-1.2.1/docs/Control-Monad-Trans-Resource.html

BTW, I'm not sure that `Program` is async exception safe: An exception could be thrown between these two lines for example: https://github.com/achirkin/vulkan/blob/master/vulkan-triangles/src/Lib/Program.hs#L182-L183

**Comment by achirkin** [comment]
I started with `ResourceT` implementation, but it becomes quite verbose when you need to create-detroy something many times before the program exits (would have to call `release` manually). For example, when you need to re-create a swapchain and its dependencies every time a window is resized. With the `Program` monad, in contrast, all resources lifetime is bounded by the nearest enclosing `locally` call. In theory, one could modify `RecouceT` to allow this too; and, probably, this would be a better way in a large-scale application. But I did not try it.

Yes, that is why I wrote that it would not work very well with normal exceptions. In the code you referenced, I do not catch haskell exceptions at all; I "catch" only `VulkanException`, which is, in fact, passed as a return value through continuations (hence it is not async). I also thought of changing all vulkan commands to run in some kind of `VkMonad` that would only be able to return this error; the monad would run in a single separate thread, and would not allow any `IO` actions and async exceptions at all.

BTW, you've got excellent haddocks! Very nice job!

**Comment by expipiplus1** [comment]
3.0.0.0 closes this issue pretty thoroughly, in fact the C-level bindings have been dropped here.

**Comment by expipiplus1** [comment]
Sorry for the 2 year delay :)

> I started with `ResourceT` implementation, but it becomes quite verbose when you need to create-detroy something many times before the program exits (would have to call `release` manually). For example, when you need to re-create a swapchain and its dependencies every time a window is resized. With the `Program` monad, in contrast, all resources lifetime is bounded by the nearest enclosing `locally` call. In theory, one could modify `RecouceT` to allow this too; and, probably, this would be a better way in a large-scale application. But I did not try it.

It should be possible to do this by nesting calls to `runResourceT`

> BTW, you've got excellent haddocks! Very nice job!

Thanks! If you'd like to share these for `vulkan-api` I'd be happy to neaten up the documentation extraction code. It takes the path to the man pages and returns a function with the type (more or less) `Documentee -> Maybe Text`

**Comment by achirkin** [comment]
Huh, yes, that would be cool! Though I am not sure when I have time to come back to `vulkan-api` to integrate that.
