### ISSUE TITLE
GHC 8.6.3 : vector-sized needs updating to 1.2.*

### ISSUE THREAD

**Issue by Althar93** [expipiplus1/vulkan#38]
Trying to get vulkan to build with 'cabal' with GHC 8.6.3 currently fails due to the dependency : "vector-sized" which is still ">= 0.1 && < 1.1". I have compiled vulkan manually with vector-sized-1.2.* & this seems to work.

Should the version dependency be updated?

Thanks.

**Comment by expipiplus1** [comment]
Thanks for the report, sorry for letting it slip past!

I've just merged a PR which should address this.
