### ISSUE TITLE
UUIDs can put unprintable characters in the Show instance

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#50]
Seems like more of an issue with bytestring.

We could:
- Write the show instance by hand to avoid this
- Use a different type than bytestring for these
  - A newtype around bytestring which prints nicely?

**Comment by dpwiz** [comment]
You can run them through [base16-bytesting](https://hackage.haskell.org/package/base16-bytestring/docs/Data-ByteString-Base16.html) without much effort and dependencies.

**Comment by expipiplus1** [comment]
Yeah, it's just a case of bothering to write the `Show` instance for the records with UUIDs in by hand instead of `deriving Show`. 

Not sure I'll use base16-bytestring for showing though, as that would violate `read . show = id` (unless the read instance was changed accordingly. It shouldn't be too hard to print them as `"\x123\x45blahblah"`

**Comment by expipiplus1** [comment]
Ah, this is a bug in pretty-simple, not bytestring.
