### ISSUE TITLE
vulkan failed to build for ghc 9.8.2

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [expipiplus1/vulkan#531]
ghc 9.8.2 complains of conflicting definitions for  'Extends' 
[log.txt](https://github.com/user-attachments/files/15513795/log.txt)

**Comment by alt-romes** [comment]
Here’s a fix: https://github.com/expipiplus1/vulkan/pull/526

I still need to figure out how to properly apply it to the bindings at generation time (@expipiplus1)
