### ISSUE TITLE
Add buffer-binding example

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#55]
Porting memory management from C++ examples is a bit overwhelming :sweat_smile:

**Comment by expipiplus1** [comment]
Great idea.

You might want to look at https://hackage.haskell.org/package/VulkanMemoryAllocator, Haskell bindings to https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/

I'll release a new version of vulkan and VMA today with some breaking changes, so watch out for that :)

**Comment by expipiplus1** [comment]
I've added an offscreen rendering example (todo comments) which [uses VMA](https://github.com/expipiplus1/vulkan/pull/53/commits/7a153f153d4118a9d8f77bc3d05bc91c3bcf2648#diff-7cc881913215bf70d4756d67f6ec2570R207-R209), although it doesn't bind any buffers in shaders. 

I'll do vertex/index buffers next I think.

**Comment by dpwiz** [comment]
Yep. Using VMA was a breeze. Alas, no buffer-backed triangles for me, yet. I get only the grey background with random flashes of color.

BTW: after using `withBuffer` renderdoc-1.7 crashes the app with a Warning:

> VkPhysicalDeviceBufferDeviceAddressFeaturesEXT.bufferDeviceAddressCaptureReplay is false, can't support capture of VK_EXT_buffer_device_address

**Comment by expipiplus1** [comment]
@dpwiz for the renderdoc crash it looks as though your Vulkan implementation doesn't support a feature renderdoc wants for some reason, do you think it's due to the Haskell bindings?

**Comment by dpwiz** [comment]
I'm quite sure I should enable something for this to work. Just posted a note here since using renderdoc is quite common and most would be expecting it to work.

**Comment by expipiplus1** [comment]
@dpwiz I modified the `offscreen` example to use a vertex and input buffer (based on https://vulkan-tutorial.com/Vertex_buffers)

See the diff here: https://github.com/expipiplus1/vulkan/commit/e77f58f7e1a33783900746c18e659722dbc2edd8

I don't think I'll merge this as is because I'd like to keep the offscreen example as concise as possible. I'll close this issue when an example of using these buffers makes it into the repo but for now I hope that this helps you.

**Comment by dpwiz** [comment]
BTW, I've found that I accidentally skipped over an entire chapter in tutorial where they set up `vertexInputState` and now it works :sweat_smile:

I'll keep this diff under the pillow while plowing further, thank you!

**Comment by expipiplus1** [comment]
Closed with compute shader example

**Comment by dpwiz** [comment]
Wow. This way I can have gravity tensor precomputed everywhere at once and make bots pathfind themselves around :thinking:

**Comment by expipiplus1** [comment]
@dpwiz sounds cool. Is your project online somewhere?

**Comment by dpwiz** [comment]
I do some newbie gamedev on [gitlab](https://gitlab.com/users/dpwiz/projects). The bots could use some GPU help in [this one](https://gitlab.com/dpwiz/spacemar), after the thorough rewrite in Vulkan first ofc.

**Comment by expipiplus1** [comment]
I'll have to take a look, thanks!

BTW, I released 3.3 and [quite a few things have changed](https://hackage.haskell.org/package/vulkan-3.3/changelog), it should be a fairly mechanical upgrade though.
