### ISSUE TITLE
Rendering to video

### ISSUE THREAD

**Issue by locallycompact** [expipiplus1/vulkan#56]
Hi, is there a way to take a vulkan haskell program and render it to image/video headlessly in CI?

**Comment by expipiplus1** [comment]
I've just finished an offscreen rendering example https://github.com/expipiplus1/vulkan/blob/master/examples/offscreen/Main.hs 

It:
- Renders a triangle into an image
- Copies the image to another image mapped on the CPU
- Writes the image as a png with JuicyPixels

Is this the kind of thing you're looking for?

For encoding video files [ffmpeg-light](https://hackage.haskell.org/package/ffmpeg-light) has worked well for me in the past.

**Comment by expipiplus1** [comment]
If you're talking about taking an existing Vulkan program and running this 'offscreen' then that's out of scope for this package, no doubt that has already been done with some layer which intercepts the swapchain commands.

**Comment by locallycompact** [comment]
> I've just finished an offscreen rendering example https://github.com/expipiplus1/vulkan/blob/master/examples/offscreen/Main.hs
> 
> It:
> 
>     * Renders a triangle into an image
> 
>     * Copies the image to another image mapped on the CPU
> 
>     * Writes the image as a png with JuicyPixels
> 
> 
> Is this the kind of thing you're looking for?
> 
> For encoding video files [ffmpeg-light](https://hackage.haskell.org/package/ffmpeg-light) has worked well for me in the past.

That sounds like what I need. May I incorporate this as the stock example for https://shakebook.site/docs/? This is my use case basically, and I want to make some sites with diagrams rendered with vulkan, but I need to spin up a lot on vulkan first. :)

**Comment by expipiplus1** [comment]
Feel free :)

Must be some pretty exciting diagrams to want to render them on the GPU!

It's possible that the offscreen example is subtly incorrect though.
Although it runs fine with my nvidia card it doesn't work with swiftshader.
If you'd be so kind as to tell me what driver you're using and if it works
for you that would be great.

Also feel free to close this issue unless there are any clarifications
you'd like on the example program.
