### ISSUE TITLE
Make bracket function naming more consistent

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#66]
At the moment most bracket commands have `with` or `cmdWith` as a prefix. The exception is `useCommandBuffer`. This was so named because there's already a function called `withCommandBuffers` (notice the `s`).

I think it might be nicer to distinguish *all* the `Begin`/`End` pairs by having `use` as a prefix instead of `with`.

The alternative is having `withCommandBuffer` (which begins and ends a command buffer) and `withCommandBuffers` (which creates and destroys command buffers)

It's also slightly strange having `with` as a prefix (and calling these functions bracketing functions) when they no longer necessarily call `bracket`. I think this is probably ok though as `with...` is enough of an idiom in Haskell to get the point across.

CC @dpwiz

**Comment by dpwiz** [comment]
It makes sense to remove `cmd` prefix since those are wrappers and not actual Vulkan commands.

I spot-checked some of the `cmdWith`s and they don't really need the bracketing, moving them further away from the `withXXx` idiom.

If there are no exceptions to that, I'm in support of `use`/`with` demarcation and removal of unused bracket arguments :+1:

**Comment by expipiplus1** [comment]
I think I'd prefer (weakly) to keep the `cmd` prefix, although they're not strictly commands, they are only valid while recording a command buffer. Admittedly it does look a little strange doing `cmdUseRenderPass ... $ \b e -> ...`. It's also useful when (because of the continuation) they do end up calling a `cmd` command (such as in `cmdUseRenderPass ... bracket_ $ do ...`)

**Comment by expipiplus1** [comment]
Perhaps an alternative would be `useCmdRenderPass` but the verb-noun-noun scans much worse than noun-verb-noun `cmdUseRenderPass`

**Comment by expipiplus1** [comment]
well, they don't need the exception handling characteristics of `bracket_` but it does save having to make variable names for `b` and `e` and remember to call them

**Comment by dpwiz** [comment]
How about `useXxx xxx beginArgs action` as a shortcut for `cmdBeginXxx xxx beginArgs >> action >> cmdEndXxx xxx`?

If someone needs to add wrappers they could wrap the `action` block or the entire `useXxx ..`.

**Comment by expipiplus1** [comment]
Yeah, if the exception handling properties aren't ever necessary it's hard to think why one would pass anything but `between` to the current bracketing functions. In fact, allowing people to put these regions in `ResourceT` or similar is asking for trouble.

I think I'd still prefer to call it `cmdUseXxx` though as it is calling `cmdBeginXxx`, making sure in the documentation to inform the user that it's not an actual Vulkan `cmd`.

Can implement tomorrow, getting late here.

**Comment by expipiplus1** [comment]
@dpwiz the "between" brackets are implemented [here](https://github.com/expipiplus1/vulkan/pull/68/commits/1d8f8027c04ad40e36fff1a15ca3e10a5c5ae50a#diff-2a7b4796a37dd996ae3851d475f8050dR726-R733)
