### ISSUE TITLE
Validation layers spam logs with VMA-induced warning

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#79]
Due to unfixable warning in VMA every buffer update in the pool having an Image somewhere would emit a validation message:

> Mapping an image with layout VK_IMAGE_LAYOUT_something_something can result in undefined behavior if this memory is used by the device. Only GENERAL or PREINITIALIZED should be used.
>
> https://www.reddit.com/r/vulkan/comments/ekx8c4/suppress_vma_warnings_in_validation_layers/

This results in a message emitted every frame, flooding the output and botching FPS.

Debug handler in `vulkan-utils` could use some fast warning suppression mechanism.

**Comment by expipiplus1** [comment]
That is unfortunate. I guess exposing two functions one which suppresses these messages and the current "print all" version would be easiest.

**Comment by dpwiz** [comment]
After upgrading to Ubuntu 20.04 I've get some 32bit vulkan libraries installed. Validator tries to load them and emits an validation error. Since I'm using the fatal callback, my app gets aborted.

This is an another instance of "counterhelpful" validation messages that only could be ignored.

**Comment by dpwiz** [comment]
Here's one from Godot people: https://github.com/godotengine/godot/pull/36454/files

**Comment by expipiplus1** [comment]
That one seems sensible to copy over

**Comment by dpwiz** [comment]
Huh. As I went to add those un-warnings I did a negative test... and the VMA warnings are gone. Perhaps installing a recent-ish lunarg sdk fixed this.

**Comment by expipiplus1** [comment]
Cool, glad to see it's fixed in any case :)
