### ISSUE TITLE
Generate safe calls for long running operations

### ISSUE THREAD

**Issue by expipiplus1** [expipiplus1/vulkan#96]
There's no clear specification of which operations are "long running". I think that those which can return "VK_TIMEOUT" would be a good start.

This is important stopping GC for such a potentially long time while waiting on a fence or something is not great.

**Comment by expipiplus1** [comment]
The functions are  `vkWaitForFences` `vkWaitSemaphores` `vkAcquireNextImageKHR` `vkAcquireNextImage2KHR` `vkAcquireProfilingLockKHR`

**Comment by expipiplus1** [comment]
Probably `vkDeviceWaitIdle` and `vkQueueWaitIdle` too

**Comment by dpwiz** [comment]
I thought GC wouldn't kick in anyway if there are no allocations going on and waiting on something should do none. Are you thinking of concurrent environment where GC can jump in from another thread?

**Comment by expipiplus1** [comment]
Exactly
