### ISSUE TITLE
Derive Generic

### ISSUE THREAD

**Issue by jmcarthur** [expipiplus1/vulkan#99]
Especially considering how boilerplatey code using Vulkan typically is, it seems like it might be pretty useful for all these large records and such to derive Generic.

(The recent flurry of activity in this project is incredible. Keep up the great work!)

**Comment by expipiplus1** [comment]
Good idea.

I have in the back of my mind a plan to (once we have RecordDotSyntax)
switch to (or at least experiment with) keeping the C representation around
in a ByteArray and just peek and poke that when one gets or sets members.
This is quite incompatible with generics. OTOH I suspect that this won't
actually be of any benefit as nearly all structs are consumed just once
(and also quite quickly after creation).

There's also the concern of generated code size. This library is already
quite large.

I don't think these are hard blockers though, so expect to see this in the
next release.

**Comment by dpwiz** [comment]
I fear adding such derivation would send compilation time through the roof.

But maybe this could be put under a flag.

**Comment by expipiplus1** [comment]
Implemented in #105 

TBH it didn't make that much difference in compile times or package size: 3m30s vs 3m42s and 46M vs 48M for `libHSvulkan-3.3-inplace.a`
